include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: warning
    todo: warning
    sdk_version_async_exported_from_core: ignore
    dead_code: warning
    invalid_assignment: warning
  exclude:
    - "test/**"

linter:
  rules:
    public_member_api_docs: false