name: digital_alarm_clock
description: Classic digital alarm clock.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clock_helper:
    path: ../flutter_clock_helper
  segment_display: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.1

flutter:
  uses-material-design: true
